version: 0.2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # Need to specify racket since it's used in the codebase
    racket: "8.14"  

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
