version: 2

# Set the OS and runtime used to build the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install sphinx furo sphinx-copybutton myst-parser
    post_build:
      - echo "Documentation build completed"

# Build documentation in additional formats such as PDF and ePub
formats:
  - pdf
  - epub
