version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py
  # Add this line:
  builder: "html"
  fail_on_warning: true

python:
  install:
    - requirements: requirements.txt

# Add this section:
formats:
  - pdf
  - epub
